spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/personal
        username: root
        password: root
        hikari:
            connection-timeout: 5000
            maximum-pool-size: 25
    jpa:
        hibernate:
            ddl-auto: none
server:
    port: 8001

#mybatis&&通用Mapper
mybatis-plus:
    #如果不是纯注解 mapper接口对应的.xml文件
    mapper-locations: classpath:mapper/**/*Mapper.xml
    type-aliases-package: com.jason.demo.entity
    global-config:
        #刷新mapper 调试神器
        refresh-mapper: true
        db-config:
            db-type: mysql
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        cache-enabled: false
        map-underscore-to-camel-case: true  #使用驼峰法映射属性

    logging:
        config: log4j2.xml
        level:
            com.jason.demo: trace
